# Generated by Django 5.0.3 on 2024-07-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time',
            field=models.TimeField(),
        ),
    ]
